train_data : "pikatchu/"
val_data : "rondoudou/"
target_size: [224,224]
normalization: "percentile"
architecture: "cnn_classifier"
batchsize: 4
lr: 0.0001
epoch: 1000
early_stopping: 10
criterion: "CrossEntropy"
optimizer: "Adam"
data_augmentation: False
conversion: "L" # ["L","RGB"]