# Spatial augmentation
do_affine_transform: False
affine_transform_prob: 0.5
rotate_range: 0.5236
scale_range: [0.85, 1.15]

# Gaussian noise
do_gaussian_noise: False
gaussian_noise_prob: 0.2
gaussian_noise_mean: 0.0
gaussian_noise_std: 0.05

# Contrast adjustment
do_adjust_contrast: False
adjust_contrast_prob: 0.2
contrast_gamma_range: [0.8, 1.2]